apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain
  storageClassName: efseks
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-1d6d5b1a